### ISSUE TITLE
Shortcut for flag count

### ISSUE THREAD

**Issue by BoPeng** [idlesign/django-siteflags#7]
I was surprised that I have to write the following by myself:

```
    def bookmark_count(self):
        return get_flag_model().objects.filter(
            object_id=self.id, status=self.FLAG_BOOKMARK).count()
```
because I thought this is a very common operation and deserves a general function like

```
    def flag_count(self, status):
        return get_flag_model().objects.filter(
            object_id=self.id, status=status).count()
```

**Comment by idlesign** [comment]
Since `siteflags` is generic it allows a user to interpret status as he likes (moderation flag, like, bookmark, etc.). Count method may too involve some additional filtering logic (say depending on current user or something else). If we reserve some status ID for a certain scenario it may clash for users using that ID for another one, or it may not work since another user uses another ID for the same scenario.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
